# Generated by Django 5.2.17 on 2026-10-02 11:21

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='IPO',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('symbol', models.CharField(blank=True, help_text='NSE/BSE ticker, once known.', max_length=20)),
                ('board', models.CharField(choices=[('MAINBOARD', 'Mainboard'), ('SME', 'SME')], default='MAINBOARD', max_length=10)),
                ('status', models.CharField(choices=[('UPCOMING', 'Upcoming'), ('OPEN', 'Open'), ('CLOSED', 'Closed'), ('ALLOTTED', 'Allotment out'), ('LISTED', 'Listed'), ('WITHDRAWN', 'Withdrawn')], default='UPCOMING', max_length=10)),
                ('price_band_low', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('price_band_high', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('lot_size', models.PositiveIntegerField(blank=True, help_text='Shares per lot. Retail must bid in whole multiples of this.', null=True)),
                ('issue_size_cr', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='issue size (₹ crore)')),
                ('open_date', models.DateField(blank=True, null=True)),
                ('close_date', models.DateField(blank=True, null=True)),
                ('allotment_date', models.DateField(blank=True, null=True)),
                ('refund_date', models.DateField(blank=True, null=True)),
                ('listing_date', models.DateField(blank=True, null=True)),
                ('listing_price', models.DecimalField(blank=True, decimal_places=2, help_text='Price at listing. Used to compute realised gain.', max_digits=10, null=True)),
                ('gmp', models.DecimalField(blank=True, decimal_places=2, help_text='Unofficial, indicative only.', max_digits=10, null=True, verbose_name='grey market premium (₹)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'ipos',
                'ordering': ['-open_date', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Registrar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, unique=True)),
                ('slug', models.SlugField(max_length=60, unique=True)),
                ('status_check_url', models.URLField(blank=True, help_text='Public allotment-status page for this registrar.')),
                ('website', models.URLField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'registrars',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('RETAIL', 'Retail'), ('SHNI', 'S-HNI (₹2–10L)'), ('BHNI', 'B-HNI (above ₹10L)'), ('EMPLOYEE', 'Employee'), ('SHAREHOLDER', 'Shareholder')], default='RETAIL', max_length=12)),
                ('status', models.CharField(choices=[('DRAFT', 'Not applied'), ('APPLIED', 'Applied'), ('ALLOTTED', 'Allotted'), ('PARTIAL', 'Partially allotted'), ('REJECTED', 'Not allotted'), ('REFUNDED', 'Refunded'), ('WITHDRAWN', 'Withdrawn')], default='DRAFT', max_length=10)),
                ('lots', models.PositiveSmallIntegerField(default=1)),
                ('bid_price', models.DecimalField(decimal_places=2, help_text='Price bid per share. Usually the cut-off price.', max_digits=10)),
                ('shares_allotted', models.PositiveIntegerField(default=0)),
                ('application_number', models.CharField(blank=True, help_text='From your broker. Some registrars accept it instead of a PAN.', max_length=40)),
                ('bank_reference', models.CharField(blank=True, help_text='ASBA / UPI mandate reference.', max_length=60)),
                ('notes', models.TextField(blank=True)),
                ('checked_at', models.DateTimeField(blank=True, help_text='When allotment was last checked for this application.', null=True)),
                ('applied_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applications', to=settings.AUTH_USER_MODEL)),
                ('pan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applications', to='accounts.panprofile')),
                ('ipo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applications', to='ipos.ipo')),
            ],
            options={
                'db_table': 'applications',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='ipo',
            name='registrar',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ipos', to='ipos.registrar'),
        ),
        migrations.CreateModel(
            name='StatusEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_status', models.CharField(blank=True, max_length=10)),
                ('to_status', models.CharField(max_length=10)),
                ('source', models.CharField(choices=[('MANUAL', 'Entered by user'), ('REGISTRAR', 'Read from registrar'), ('SYSTEM', 'Automatic')], default='MANUAL', max_length=10)),
                ('note', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='ipos.application')),
            ],
            options={
                'db_table': 'status_events',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='application',
            index=models.Index(fields=['owner', '-created_at'], name='application_owner_i_91f1fb_idx'),
        ),
        migrations.AddIndex(
            model_name='application',
            index=models.Index(fields=['owner', 'status'], name='application_owner_i_5a83ac_idx'),
        ),
        migrations.AddConstraint(
            model_name='application',
            constraint=models.UniqueConstraint(fields=('ipo', 'pan'), name='uniq_application_per_pan_per_ipo'),
        ),
        migrations.AddConstraint(
            model_name='application',
            constraint=models.CheckConstraint(condition=models.Q(('lots__gte', 1)), name='application_has_at_least_one_lot'),
        ),
        migrations.AddIndex(
            model_name='ipo',
            index=models.Index(fields=['status'], name='ipos_status_ed96c6_idx'),
        ),
        migrations.AddIndex(
            model_name='ipo',
            index=models.Index(fields=['-close_date'], name='ipos_close_d_7a707f_idx'),
        ),
        migrations.AddIndex(
            model_name='ipo',
            index=models.Index(fields=['-allotment_date'], name='ipos_allotme_9100a0_idx'),
        ),
        migrations.AddConstraint(
            model_name='ipo',
            constraint=models.CheckConstraint(condition=models.Q(('close_date__gte', models.F('open_date'))), name='ipo_closes_after_it_opens'),
        ),
        migrations.AddIndex(
            model_name='statusevent',
            index=models.Index(fields=['application', '-created_at'], name='status_even_applica_09d5df_idx'),
        ),
    ]
