# Generated by Django 5.2.17 on 2026-10-03 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ipos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ipo',
            name='dates_estimated',
            field=models.BooleanField(default=False, help_text='Allotment/listing dates were estimated from the SEBI T+3 timeline, not published by the exchange.'),
        ),
        migrations.AddField(
            model_name='ipo',
            name='last_synced_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ipo',
            name='registrar_ref',
            field=models.CharField(blank=True, help_text="This issue's id on the registrar's own status page. Filled in automatically.", max_length=80),
        ),
        migrations.AddField(
            model_name='ipo',
            name='source',
            field=models.CharField(choices=[('MANUAL', 'Entered by hand'), ('NSE', 'Synced from NSE')], default='MANUAL', max_length=10),
        ),
        migrations.AddConstraint(
            model_name='ipo',
            constraint=models.UniqueConstraint(condition=models.Q(('symbol', ''), _negated=True), fields=('symbol',), name='uniq_ipo_symbol_when_set'),
        ),
    ]
